version: '3'
services:
    web:
        build: .
        command: uvicorn pywsgi --host 0.0.0.0 --port 5000
        dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=pywsgi.py
        env_file:
            - .env
        depends_on:
            - db
            - redis
    db:
        image: postgres:13
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=!AdMiN!
            - POSTGRES_DB=auth
        ports:
            - 5433:5432
        volumes:
            - flask_polls_data:/var/lib/postgresql/data
    redis:
        image: 'docker.io/bitnami/redis:6.0-debian-10'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        volumes:
            - 'redis_data:/bitnami/redis/data'

volumes:
    redis_data: